// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUgBBpEX4uqa6YYCoxDeZriITsu3_USBU',
    appId: '1:845304979861:web:224cedb65a1cfea69fd69c',
    messagingSenderId: '845304979861',
    projectId: 'rflutter-d4cfd',
    authDomain: 'rflutter-d4cfd.firebaseapp.com',
    storageBucket: 'rflutter-d4cfd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOrVTS9YcCRYrrAjnJIb7ppbQM0lvPYkc',
    appId: '1:845304979861:android:3098754bfa17e14d9fd69c',
    messagingSenderId: '845304979861',
    projectId: 'rflutter-d4cfd',
    storageBucket: 'rflutter-d4cfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCumP-dc1ja-ORvOTzopUQZcSt306blB2E',
    appId: '1:845304979861:ios:eb409b04a6e419bb9fd69c',
    messagingSenderId: '845304979861',
    projectId: 'rflutter-d4cfd',
    storageBucket: 'rflutter-d4cfd.appspot.com',
    iosClientId: '845304979861-8ea85u5n4b7g0sl297bhgdr39m7t0s61.apps.googleusercontent.com',
    iosBundleId: 'com.example.rflutter',
  );
}
